dist: trusty

language: node_js

services: mysql

before_install:
  - mysql -e 'CREATE DATABASE nested_set_test;'
  - npm install

env:
  global:
    - SNS_DB=nested_set_test
    - SNS_USER=travis

jobs:
  include:
    - stage: test
      install: npm install sequelize@4 mysql2@1
      node_js: '10'
      script: npm run test
    - stage: test
      install: npm install sequelize@5 mysql2@1
      node_js: '10'
      script: npm run test
    - stage: test
      install: npm install sequelize@6 mysql2@2
      node_js: '10'
      script: npm run test
    - stage: test
      install: npm install sequelize@4 mysql2@1
      node_js: '12'
      script: npm run test
    - stage: test
      install: npm install sequelize@5 mysql2@1
      node_js: '12'
      script: npm run test
    - stage: test
      install: npm install sequelize@6 mysql2@2
      node_js: '12'
      script: npm run test
    - stage: test
      install: npm install sequelize@4 mysql2@1
      node_js: '14'
      script: npm run test
    - stage: test
      install: npm install sequelize@5 mysql2@1
      node_js: '14'
      script: npm run test
    - stage: test
      install: npm install sequelize@6 mysql2@2
      node_js: '14'
      script:
        - npm run test-with-coverage
        - npm run report-coverage

stages:
  - test
